### ISSUE TITLE
RGB viewer fails on empty annotations

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#123]
I know this was addressed previously; however, I think I'm getting a different error now than I was before for empty labels. Before it would crash immediately upon opening. Now it opens with empty labels, but upon trying to draw new labels, fails with the attached error message. If this is the same bug that just hasn't been merged into RGB branch yet feel free to go ahead and close this issue

![image](https://user-images.githubusercontent.com/13770365/77504246-0e39d700-6e1d-11ea-9d85-1751b2d1e596.png)

**Comment by geneva-miller** [comment]
I thought I had fixed that aspect of it but clearly not! At least in RGB mode. Can you send me the file? I'll fix this for RGB mode and make sure it's working in normal mode (as I think it should be).

**Comment by ngreenwald** [comment]
[blank_fov_Eliot_row_0_col_5_slice_0.npz.zip](https://github.com/vanvalenlab/caliban/files/4382045/blank_fov_Eliot_row_0_col_5_slice_0.npz.zip)
Sure thing, see attached

**Comment by geneva-miller** [comment]
Found the bug. Basically, I created the RGB class with the expectation that it wouldn't have more than one frame at a time, and most of the code reflects that. But there was one line left over from the original npz class that was looking for the information on which slices a label was in--which is not encoded in RGB. Fixed for now, but a more stable solution would be to make RGB robust to either case, since others may have multichannel images across z or t.
