### ISSUE TITLE
Restrict RGB keybinds

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#133]
To prevent confusion, I think we can further restrict the set of keybinds that are available by default in RGB mode. 

I've created a whitelist of what I think should be included, let me know if you think I'm missing any obvious ones. 

pixel mode:

- up/down arrow keys: brush size
- p - label picker
- x - erase mode
- n - new unused label

labels mode:
x - delete cell
r - combine cells

**Comment by geneva-miller** [comment]
Conversion brush, -/= changing brush value, highlight cycling with -/= are ones I would suggest keeping (shift and alt click as well). They don't need to be explicitly explained in each job but I would rather keep them in for now instead of having to re-enable them for the next rgb job.

In other words, disabling:
- ability to toggle off highlighting (have it always be on)
- create new
- threshold
- watershed
- swap

I'm on the fence about hole-filling.

**Comment by ngreenwald** [comment]
I agree with all of those. Is create new different from n? 

Also I didn't include Z/L in my list for keeps, but I think we should keep them both.
