### ISSUE TITLE
Caliban should never make an empty track

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/caliban#16]
Before saving, the program should check to see if there are any tracks that do not contain any frames and delete them.

**Comment by geneva-miller** [comment]
Sort of fixed with #28 . Empty tracks are removed upon save, which is useful for fixing otherwise correct trk files with bad lineage info, and for preventing empty tracks from being saved into future lineages. Lineage-editing functions should be reviewed to fix this behavior instead of relying on catching it at save.

**Comment by MekWarrior** [comment]
Solved by #28 and #31
